### ISSUE TITLE
Signup Not Secure

### ISSUE THREAD

**Issue by naqaden** [veloren/site#1]
Signup values are shown in plain text in the address bar.
![2024-12-29 11-20-02](https://github.com/user-attachments/assets/21aa767b-ec82-4e79-afb0-49ae6313c65d)

**Comment by zesterer** [comment]
Same here

**Comment by naqaden** [comment]
I used Firefox. I just tried again and reproduced the issue.

Console showed:
```
Uncaught TypeError: window.fieldRepeatValidity is not a function
    onchange https://veloren.net/account/create-account/?username=testusername&password=testpassword&password_repeat=testpassword:1
[create-account:1:8](https://veloren.net/account/create-account/?username=testusername&password=testpassword&password_repeat=testpassword)
    onchange https://veloren.net/account/create-account/?username=testusername&password=testpassword&password_repeat=testpassword:1
    _fillForm resource://gre/modules/LoginManagerChild.sys.mjs:3051
    loginsFound resource://gre/modules/LoginManagerChild.sys.mjs:2101
```

I think it's related to my privacy extensions. After toggling some, I could no longer reproduce the issue. My best guess is my user agent randomizer tricked the site in a bad way, and I can't reproduce it now because I don't know which fake agent caused this.

I'm comfortable calling this user error.

**Comment by zesterer** [comment]
We had a discussion about this. @Imberflur suggested that it might be because your browser has JavaScript disabled. There is a `event.preventDefault();` call that tells the sign-up form to not submit data as query parameters and instead perform a POST to the auth server, but if this doesn't occur then it might be inserting the form elements into the URL.

Although there's certainly an aspect of your configuration being non-standard, I think this is still a relevant issue: it seems like a malicious auth server *could* pull the password from the URL parameters despite it usually being hashed client-side, so it would be a good idea to find a non-JavaScripty way of disabling the default form behaviour.

**Comment by naqaden** [comment]
I had to enable js right away (uMatrix) as the form doesn't show up without it, and I saved that rule. Maybe starting without js caused lingering issues, but would they linger as far as my second attempt days later, after the replies here? I would have restarted my browser and PC a couple times by then.

Maybe our theories combined have more traction, where my user agent randomizer tricked some js into making calls it couldn't execute, resulting in broken scripts? I am not well versed in this stuff. Happy to dig further if there's anything else I can test.

**Comment by Imberflur** [comment]
Looking at your error above, the code that uses `window.fieldRepeatValidity` is before it sets up `postToBackendNewAccount` which is called by the the submit event for the form `<form onsubmit="window.postToBackendNewAccount(event)">`. So the `postToBackendNewAccount` call probably fails because it doesn't exist, thus `event.preventDefault();` is never called. There's probably a way to improve this by not showing the form unless the js execution reaches a certain point?

https://gitlab.com/veloren/site/-/blob/1b9d016efa3a2e28d8815b5978bd1b8265fb47b7/static/js/account.js
https://gitlab.com/veloren/site/-/blob/1b9d016efa3a2e28d8815b5978bd1b8265fb47b7/content/account/create-account.md?plain=1

**Comment by Imberflur** [comment]
Actually that error doesn't look like it would come from the code setting `window.fieldRepeatValidity` :thinking:

But if whatever caused it to not be a function had the same effect on `window.postToBackendNewAccount`, then the conclusion is similar.
